server:
  port: 8080
management:
  security:
    enabled: false
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lecourtoisn/randomconfig.git
          clone-on-start: true

